application: godoctor-www
version: 1
runtime: go
api_version: go1

handlers:
- url: /(doc|install)\.html
  script: _go_app
- url: /exe/.*
  script: _go_app
- url: /
  static_files: htdocs/index.html
  upload: htdocs/index.html
- url: /demo/
  static_files: htdocs/demo/index.html
  upload: htdocs/demo/index.html
- url: /(.*)
  static_files: htdocs/\1
  upload: htdocs/.*

nobuild_files:
- ^(go)/
- ^(generated)/
- ^(htdocs)/
